[project]
name = "notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.13.2",
    "jupyterlab>=4.5.0",
    "loguru>=0.7.3",
    "orjson>=3.11.4",
    "polars>=1.35.2",
    "python-dotenv>=1.2.1",
]
